---
services:
  wormhole:
    image: wormhole
    build:
      context: .
      dockerfile: ./compose/Dockerfile.app
    volumes:
      - "./wormhole:/code/app"
      - "./compose/data:/mirror"
    networks:
      - wormhole_net
    command:
      - "uvicorn"
      - "app.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"
      #- "--root-path"  # use these two lines if you are running behind a proxy
      #- "/wormhole"     # that uses a subpath, needs to be different from the download subpath
  webserver:
    image: webserver
    build:
      context: ./compose
      dockerfile: Dockerfile.nginx
    volumes:
      - "./compose/data:/data/ansible:ro"
    ports:
      - "80:80"
    networks:
      - wormhole_net

networks:
  wormhole_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1337
